controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins:
      - nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController
    RegulatedPurePursuitController:
      desired_linear_vel: 0.5
      min_approach_linear_velocity: 0.05
      max_allowed_linear_accel: 2.0
      max_allowed_linear_decel: 2.0
      # Add more parameters as needed for your specific robot and environment
