slam_toolbox:
  ros__parameters:
    use_sim_time: True
    # General mapping parameters
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    mode: async
    # For more parameters, refer to the slam_toolbox documentation:
    # http://docs.ros.org/en/humble/p/slam_toolbox/index.html
    # Example parameters (uncomment and adjust as needed):
    # resolution: 0.05
    # minimum_travel_distance: 0.2
    # minimum_travel_angle: 0.1
    # transform_tolerance: 0.5
    # max_laser_range: 8.0
    # min_laser_range: 0.1
    # laser_max_range: 8.0
    # laser_min_range: 0.1
    # use_transform_time_offset: true
    # scan_buffer_size: 10
    # throttle_scans: 1
    # debug_logging: false
