# For full Nav2 parameters, refer to:
# https://navigation.ros.org/configuration/packages/index.html
# This is a minimal set for mapping with an existing map server.

amcl:
  ros__parameters:
    use_sim_time: true
    set_initial_pose: false
    # Other AMCL parameters as needed for your robot
    # For example:
    # min_particles: 500
    # max_particles: 3000
    # kld_err: 0.05
    # kld_z: 0.99
    # update_min_d: 0.25
    # update_min_a: 0.2
    # resample_interval: 1
    # transform_tolerance: 0.1
    # recovery_alpha_slow: 0.001
    # recovery_alpha_fast: 0.1
    # initial_pose: {x: 0.0, y: 0.0, z: 0.0, a: 0.0}
    # gui_publish_rate: 10.0
    # laser_max_range: 3.5
    # laser_min_range: 0.1
    # laser_max_beams: 30
    # laser_z_hit: 0.5
    # laser_z_short: 0.05
    # laser_z_max: 0.05
    # laser_z_rand: 0.5
    # laser_sigma_hit: 0.2
    # laser_lambda_short: 0.1
    # laser_lambda_max: 0.05
    # laser_model_type: "likelihood_field"
    # laser_likelihood_max_dist: 2.0
    # update_topic: "scan"
    # tf_broadcast: true
    # global_frame_id: map
    # odom_frame_id: odom
    # base_frame_id: base_link

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath", "KeepOut"] # Example, adjust as needed

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      # Parameters for RegulatedPurePursuitController
      desired_linear_vel: 0.5
      max_linear_accel: 2.5
      max_angular_accel: 3.2
      # ... other parameters

    KeepOut:
      plugin: "nav2_keepout_filter::KeepoutFilter"
      # Parameters for KeepoutFilter

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"] # Example, adjust as needed

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      # Parameters for NavfnPlanner
      # ...

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    # Other BT Navigator parameters as needed

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    # Other Waypoint Follower parameters as needed

