planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins:
      - nav2_smac_planner/SmacPlannerHybrid
    SmacPlannerHybrid:
      allow_unknown: true
      tolerance: 0.5
      # Add more parameters as needed for your specific robot and environment
